services:
  selenium-firefox:
    image: selenium/standalone-firefox:latest
    container_name: selenium-firefox
    ports:
      - "4444:4444"
    shm_size: 2gb
    environment:
      - SE_ENABLE_TRACING=false
  backend:
    container_name: cinetour-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
    volumes:
      - ./src:/cinetour_backend/src
    depends_on:
      neo4j:
        condition: service_healthy
      selenium-firefox:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=neo4jpassword
      - SELENIUM_REMOTE_URL=http://selenium-firefox:4444/wd/hub
  neo4j:
    image: neo4j:5.15.0
    container_name: cinetour-neo4j
    restart: always
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 2G
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    healthcheck:
      test:
        [
          "CMD",
          "cypher-shell",
          "-u",
          "neo4j",
          "-p",
          "neo4jpassword",
          "RETURN 1",
        ]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 30s

volumes:
  neo4j-data:
  neo4j-logs:
