services:
  selenium-firefox:
    image: selenium/standalone-firefox:latest
    container_name: selenium-firefox
    ports:
      - "4444:4444"
    shm_size: 2gb
    environment:
      - SE_ENABLE_TRACING=false
  cinetour-backend:
    container_name: cinetour-backend
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./src:/cinetour_backend/src
    depends_on:
      selenium-firefox: 
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: network
      CINETOUR_NETWORK_DB_URL: "jdbc:mysql://127.0.0.1:3307/cinetour?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      CINETOUR_NETWORK_DB_USER: "cinetour_net"
      NETWORK_DB_PASSWORD: ${NETWORK_DB_PASSWORD:-}
    env_file:
      - .env