services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    shm_size: 2gb
    environment:
      - SE_ENABLE_TRACING=false
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
    depends_on:
      mysql:
        condition: service_healthy
      selenium-chrome: 
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cinetour
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpassword
      - SELENIUM_REMOTE_URL=http://selenium-chrome:4444/wd/hub
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cinetour
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    healthcheck:
      test: ["CMD", "mysql", "-u", "dbuser", "-pdbpassword", "-e", "USE cinetour;"]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 20s

volumes:
  mysql-data:
