spring.application.name=CineTour
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${CINETOUR_NETWORK_DB_URL}
spring.datasource.username=${CINETOUR_NETWORK_DB_USER}
spring.datasource.password=${CINETOUR_NETWORK_DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080

# HikariCP settings
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-1
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=60000

# Selenium
selenium.remote.url=http://localhost:4444

# Logging SQL queries
logging.level.net.ttddyy.dsproxy.listener=debug